Repository WildCodeSchool/2022-03-php-orleans-project-splitscreen, pull requests merged in 2022-07, with the labels that each got.

#279 Fix admin home content
  assets/styles/homeAdmin.scss
  package-lock.json
  templates/admin/admin_home/index.html.twig
Labels: Reviewed, Conflicts resolved

#326 S04HNC51_Event_passé_futur
  composer.lock
  src/Controller/EventController.php
  src/Repository/EventRepository.php
  templates/components/_card_event.html.twig
  templates/event/index.html.twig
Labels: Conflicts resolved

#347 fixed no requiere
  src/Form/EventType.php
Labels: Reviewed

#346 ckeditor for events
  src/Form/EventType.php
  templates/event/show.html.twig
Labels: Reviewed

#350 readded route for webpack for css
  webpack.config.js
Labels: Reviewed, Fix

#353 Fix - Upload images for event pages
  templates/components/_card_event.html.twig
  templates/event/show.html.twig
Labels: Reviewed, Fix

#354 fix home actu
  templates/home/index.html.twig
Labels: Reviewed

#348 upload actu
  config/packages/vich_uploader.yaml
  migrations/Version20220704085405.php
  public/uploads/actu/.gitignore
  src/Entity/Actuality.php
  src/Form/ActualityType.php
Labels: Reviewed, Correction done

#357 c mieu
  templates/actuality/show.html.twig
Labels: Reviewed, Correction done

#352 add upload
  config/packages/vich_uploader.yaml
  migrations/Version20220704150554.php
  public/uploads/member/.gitignore
  src/Entity/Member.php
  src/Form/MemberType.php
  templates/admin/admin_member/_form.html.twig
Labels: Reviewed, Correction done

#362 bugfix
  migrations/Version20220704085405.php
Labels: Reviewed, Fix

#360 dev to main
  assets/styles/homeAdmin.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/fos_ckeditor.yaml
  config/packages/twig.yaml
  config/packages/vich_uploader.yaml
  migrations/Version20220627134054.php
  migrations/Version20220627142737.php
  migrations/Version20220704150554.php
  package-lock.json
  package.json
  public/uploads/actu/.gitignore
  public/uploads/member/.gitignore
  src/Controller/AdminAssoController.php
  src/Controller/EventController.php
  src/Controller/HomeController.php
  src/DataFixtures/HelloAssoFixtures.php
  src/DataFixtures/NetworkFixtures.php
  src/Entity/Actuality.php
  src/Entity/Event.php
  src/Entity/HelloAsso.php
  src/Entity/Member.php
  src/Form/ActualityType.php
  src/Form/EventType.php
  src/Form/HelloAssoType.php
  src/Form/MemberType.php
  src/Repository/EventRepository.php
  src/Repository/HelloAssoRepository.php
  symfony.lock
  templates/actuality/show.html.twig
  templates/admin/_navbarAdmin.html.twig
  templates/admin/admin_asso/_form.html.twig
  templates/admin/admin_asso/edit.html.twig
  templates/admin/admin_asso/index.html.twig
  templates/admin/admin_event/_form.html.twig
  templates/admin/admin_home/index.html.twig
  templates/admin/admin_member/_form.html.twig
  templates/admin/partner/_form.html.twig
  templates/components/_card_event.html.twig
  templates/components/_footer.html.twig
  templates/components/_header.html.twig
  templates/event/index.html.twig
  templates/event/show.html.twig
  templates/home/index.html.twig
  templates/legal-notice/index.html.twig
  webpack.config.js
  yarn.lock
Labels: DEV TO MAIN

#336 S04HNC54_Style_Partenaire
  assets/styles/partners.scss
  config/packages/vich_uploader.yaml
  public/uploads/partners/.gitignore
  src/Controller/AssociationController.php
  templates/admin/partner/index.html.twig
  templates/association/index.html.twig
  templates/components/_partners.html.twig
  webpack.config.js
Labels: Conflicts resolved

#369 fixed button and form style
  src/Form/NetworkType.php
  templates/admin/admin_network/_form.html.twig
  templates/admin/admin_network/edit.html.twig
  templates/admin/admin_network/index.html.twig
Labels: Reviewed, Fix

#370 fix_partners_crud fix style
  templates/admin/partner/index.html.twig
Labels: Reviewed

#371 FIX_style mentions legales
  templates/legal-notice/index.html.twig
Labels: Reviewed

#361 S05HNC46_Tournament
  migrations/Version20220704133128.php
  src/DataFixtures/EventFixtures.php
  src/DataFixtures/ParticipantFixtures.php
  src/Entity/Event.php
  src/Entity/Participant.php
  src/Form/EventType.php
  src/Form/ParticipantType.php
  src/Repository/ParticipantRepository.php
  templates/admin/admin_event/_form.html.twig
Labels: Conflicts resolved

#373 imgCards
  assets/styles/app.scss
  assets/styles/home.scss
  templates/actuality/index.html.twig
  templates/components/_card_event.html.twig
  templates/home/index.html.twig
Labels: Reviewed, Correction done, Fix

#376 fix_show_events
  templates/event/show.html.twig
Labels: Reviewed

#379 fix_footer_mentionslegs
  templates/legal-notice/index.html.twig
Labels: Reviewed

#380 fixed links
  templates/admin/_navbarAdmin.html.twig
  templates/admin/admin_home/index.html.twig
Labels: Reviewed

#381 fix_delete_dl_admin
  src/Form/ActualityType.php
  src/Form/EventType.php
  src/Form/MemberType.php
  src/Form/PartnerType.php
Labels: Reviewed

#387 redirection connexion admin
  templates/components/_footer.html.twig
Labels: Reviewed

#388 S05HNC46_JS
  assets/participants.js
  package.json
  src/Entity/Event.php
  src/Form/EventType.php
  src/Form/ParticipantType.php
  templates/admin/admin_event/_form.html.twig
  templates/admin/admin_event/edit.html.twig
  templates/admin/admin_event/new.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#391 fix_partenaire
  templates/components/_partners.html.twig
Labels: Reviewed

#395 fixed network missing div
  templates/admin/admin_network/_form.html.twig
Labels: Reviewed

#396 fix_alt_home_img
  templates/home/index.html.twig
Labels: Conflicts resolved

#383 fixed asso style
  templates/admin/admin_asso/_form.html.twig
  templates/admin/admin_asso/edit.html.twig
  templates/admin/admin_asso/index.html.twig
Labels: Reviewed, Correction done

#386 added message
  templates/admin/admin_network/index.html.twig
Labels: Reviewed, Correction done

#398 dev to main
  assets/participants.js
  assets/styles/app.scss
  package.json
  src/Entity/Event.php
  src/Form/ActualityType.php
  src/Form/EventType.php
  src/Form/MemberType.php
  src/Form/ParticipantType.php
  src/Form/PartnerType.php
  templates/actuality/index.html.twig
  templates/actuality/show.html.twig
  templates/admin/_navbarAdmin.html.twig
  templates/admin/admin_asso/_form.html.twig
  templates/admin/admin_asso/edit.html.twig
  templates/admin/admin_asso/index.html.twig
  templates/admin/admin_event/_form.html.twig
  templates/admin/admin_event/edit.html.twig
  templates/admin/admin_event/new.html.twig
  templates/admin/admin_home/index.html.twig
  templates/admin/admin_network/_form.html.twig
  templates/admin/admin_network/index.html.twig
  templates/components/_banner.html.twig
  templates/components/_card_event.html.twig
  templates/components/_footer.html.twig
  templates/components/_partners.html.twig
  templates/event/show.html.twig
  templates/home/index.html.twig
  templates/legal-notice/index.html.twig
  webpack.config.js
  yarn.lock
Labels: DEV TO MAIN

#389 fix_title_events/actu
  templates/actuality/show.html.twig
  templates/event/show.html.twig
Labels: Conflicts resolved

#390 ajout du Service Slug
  migrations/Version20220705181612.php
  src/Controller/ActualityController.php
  src/Controller/AdminActualityController.php
  src/Controller/AdminEventController.php
  src/Controller/EventController.php
  src/DataFixtures/ActualityFixtures.php
  src/DataFixtures/EventFixtures.php
  src/Entity/Actuality.php
  src/Services/Slugify.php
  templates/actuality/index.html.twig
  templates/components/_card_event.html.twig
  templates/home/index.html.twig
Labels: Conflicts resolved

#401 fixed required issue and nullable possibility
  src/Entity/Network.php
  src/Form/NetworkType.php
Labels: Reviewed

#400 Reseau cote client
  src/Controller/ContactController.php
  src/DataFixtures/NetworkFixtures.php
  templates/admin/admin_network/index.html.twig
  templates/contact/_networks.html.twig
Labels: Reviewed, Conflicts resolved

#406 fixed button admin network
  templates/admin/admin_network/index.html.twig
Labels: Reviewed, Fix

#407 S05HNC_FIX_MARGIN
  templates/event/_eventList.html.twig
Labels: Reviewed, Fix

#409 fixed link redirection to a new page
  templates/contact/_networks.html.twig
Labels: Reviewed, Fix

#414 FIX_Participant_Supp
  src/Entity/Event.php
Labels: Reviewed, Fix

#408 S05HNC_FIX_MARGIN_H
  templates/event/_eventList.html.twig
Labels: Conflicts resolved

#416 FIX_BTN_PARTICIPANT
  assets/styles/homeAdmin.scss
  src/Form/ParticipantType.php
  templates/admin/admin_event/_form.html.twig
Labels: Reviewed, Fix

#397 fix_affichage_member
  src/Controller/AssociationController.php
  templates/association/index.html.twig
  templates/components/_members.html.twig
Labels: Reviewed, Correction done

#419 fix_hello_asso
  src/Controller/DefaultController.php
  templates/components/_banner.html.twig
  templates/event/index.html.twig
  templates/home/index.html.twig
Labels: Reviewed, Correction done

#418 DEV TO MAIN
  assets/images/TOP1.png
  assets/images/TOP2.png
  assets/images/TOP3.png
  assets/styles/homeAdmin.scss
  migrations/Version20220705181612.php
  src/Controller/ActualityController.php
  src/Controller/AdminActualityController.php
  src/Controller/AdminEventController.php
  src/Controller/AssociationController.php
  src/Controller/ContactController.php
  src/Controller/DefaultController.php
  src/Controller/EventController.php
  src/DataFixtures/ActualityFixtures.php
  src/DataFixtures/EventFixtures.php
  src/DataFixtures/NetworkFixtures.php
  src/Entity/Actuality.php
  src/Entity/Event.php
  src/Entity/Member.php
  src/Entity/Network.php
  src/Entity/Participant.php
  src/Form/ActualityType.php
  src/Form/MemberType.php
  src/Form/NetworkType.php
  src/Form/ParticipantType.php
  src/Services/Slugify.php
  templates/actuality/index.html.twig
  templates/actuality/show.html.twig
  templates/admin/admin_event/_form.html.twig
  templates/admin/admin_network/index.html.twig
  templates/association/index.html.twig
  templates/components/_banner.html.twig
  templates/components/_card_event.html.twig
  templates/components/_members.html.twig
  templates/contact/_networks.html.twig
  templates/event/_eventList.html.twig
  templates/event/_participant.html.twig
  templates/event/index.html.twig
  templates/event/show.html.twig
  templates/home/index.html.twig
Labels: DEV TO MAIN

#422 fix_image_require
  src/Controller/AdminActualityController.php
  src/Controller/AdminEventController.php
  src/Controller/PartnerController.php
  src/Entity/Actuality.php
  src/Entity/Event.php
  src/Entity/Partner.php
  src/Form/ActualityType.php
  src/Form/EventType.php
  src/Form/PartnerType.php
Labels: Reviewed

#430 fix_participant
  templates/event/_participant.html.twig
Labels: Reviewed

#424 FIX_IMG_SHOW
  templates/actuality/show.html.twig
  templates/event/show.html.twig
Labels: Conflicts resolved

#423 fix_slug_event
  migrations/Version20220707144527.php
  src/Entity/Event.php
  src/Form/EventType.php
  templates/admin/admin_event/_form.html.twig
  templates/event/show.html.twig
Labels: Conflicts resolved

#432 added real content
  templates/event/_eventList.html.twig
Labels: Reviewed

#433 fix_card_actus
  templates/actuality/index.html.twig
Labels: Reviewed

#434 fix_slug_tournoi
  src/Entity/Event.php
Labels: Reviewed

#435 fix-fking-banner
  templates/event/_participant.html.twig
Labels: Reviewed

#436 fix-aos
  assets/app.js
  assets/styles/app.scss
  package.json
  templates/actuality/index.html.twig
  templates/components/_card_event.html.twig
  templates/home/index.html.twig
  yarn.lock
Labels: Reviewed

#438 Fix shadow img
  assets/styles/app.scss
  templates/contact/_contactForm.html.twig
  templates/contact/_networks.html.twig
Labels: Reviewed

#439 FIX_MEMBRES
  assets/styles/members.scss
  templates/components/_members.html.twig
  webpack.config.js
Labels: Reviewed

#444 fix-placeholdr-img-member
  assets/images/member.png
  templates/components/_members.html.twig
Labels: Conflicts resolved

#443 Fix - removed times and fixed date formats
  templates/actuality/index.html.twig
  templates/actuality/show.html.twig
  templates/components/_card_event.html.twig
  templates/event/show.html.twig
  templates/home/index.html.twig
Labels: Conflicts resolved

#446 fixed missing if
  templates/actuality/index.html.twig
Labels: Reviewed

#448 Fix - EndIf added
  templates/actuality/index.html.twig
Labels: Reviewed

#451 fix_cards_size_actus
  templates/actuality/index.html.twig
Labels: Reviewed, Fix

#452 FIX_SLUG_ADMIN
  src/Form/EventType.php
Labels: Reviewed

#453 fix_home_color_button
  templates/home/index.html.twig
Labels: Reviewed

#455 FIX_SHOW_ACTUS
  templates/actuality/show.html.twig
  templates/event/show.html.twig
Labels: Reviewed, Fix

#457 FIX_ORDRE_EVENT_ACTUS
  templates/admin/admin_actuality/_form.html.twig
  templates/admin/admin_event/_form.html.twig
Labels: Reviewed

#449 readme
  README.md
Labels: Reviewed, Correction done

#459 FIX_CONTACT_FORM
  src/Controller/ContactController.php
Labels: Reviewed

#456 FIX_PAGES_ERRORS
  public/uploads/pictures/.gitignore
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
Labels: Reviewed

#460 fixed include error and div placement
  templates/admin/admin_network/_form.html.twig
  templates/admin/admin_network/edit.html.twig
Labels: Reviewed, Fix

#461 FIX_HELP_LINK_TOURNEY
  src/Form/EventType.php
Labels: Reviewed

#486 FIX_OPPACITE_CARD_RESPONSIVE
  assets/styles/cards.scss
Labels: Reviewed, Fix

#487 FIX_TAILLE_UPLOAD
  php.ini
  src/Controller/AdminMemberController.php
  src/Entity/Actuality.php
  src/Entity/Event.php
  src/Entity/Member.php
  src/Entity/Partner.php
  src/Form/MemberType.php
Labels: Reviewed, Correction done, Fix

#490 fixed Hover
  templates/components/_members.html.twig
Labels: Reviewed, Fix

#491 DEV TO MAIN
  assets/styles/cards.scss
  php.ini
  src/Controller/AdminAssoController.php
  src/Controller/AdminMemberController.php
  src/Controller/AdminNetworkController.php
  src/Controller/PartnerController.php
  src/Entity/Actuality.php
  src/Entity/Event.php
  src/Entity/Member.php
  src/Entity/Partner.php
  src/Form/MemberType.php
  templates/admin/admin_home/index.html.twig
  templates/components/_members.html.twig
Labels: DEV TO MAIN

#492 added youtube
  src/DataFixtures/NetworkFixtures.php
Labels: Reviewed

#507 FIX_ROUTES_ADMIN
  src/Controller/AdminActualityController.php
Labels: Reviewed

#506 FIX_TITLE_ADMIN
  templates/admin/admin_actuality/edit.html.twig
  templates/admin/admin_actuality/index.html.twig
  templates/admin/admin_actuality/new.html.twig
  templates/admin/admin_asso/edit.html.twig
  templates/admin/admin_asso/index.html.twig
  templates/admin/admin_event/edit.html.twig
  templates/admin/admin_event/index.html.twig
  templates/admin/admin_event/new.html.twig
  templates/admin/admin_member/edit.html.twig
  templates/admin/admin_member/index.html.twig
  templates/admin/admin_member/new.html.twig
  templates/admin/admin_network/edit.html.twig
  templates/admin/admin_network/index.html.twig
  templates/admin/partner/edit.html.twig
  templates/admin/partner/index.html.twig
  templates/admin/partner/new.html.twig
Labels: Reviewed

#504 FIX_ARROW_ACTUS
  assets/styles/actu.scss
  templates/actuality/show.html.twig
  webpack.config.js
Labels: Reviewed

#503 FIX_ARROW
  templates/event/show.html.twig
Labels: Reviewed, Fix

#500 FIX_FLASH_CONTACT
  templates/admin/baseAdmin.html.twig
  templates/base.html.twig
  templates/contact/index.html.twig
Labels: Reviewed

#499 removed marigin for corners
  assets/styles/app.scss
Labels: Reviewed

#498 FIX_PODIUM ul + affichage
  templates/event/_participant.html.twig
  templates/event/show.html.twig
Labels: Reviewed

#497 FIX_ROUTES
  src/Controller/ActualityController.php
  src/Controller/EventController.php
Labels: Reviewed, Fix

#495 FIX_TARGET_MENTION
  templates/components/_footer.html.twig
Labels: Reviewed, Fix

#494 FIX_QUOTE
  templates/actuality/index.html.twig
  templates/association/index.html.twig
  templates/event/index.html.twig
Labels: Conflicts resolved

#501 FIX_RETOUR_ACCUEIL
  assets/styles/event.scss
  templates/event/show.html.twig
  webpack.config.js
Labels: Conflicts resolved

#510 Fix removed time
  templates/admin/admin_event/index.html.twig
Labels: Reviewed, Fix

#512 Added checkbox to "Enregister"
  templates/admin/admin_event/_form.html.twig
Labels: Reviewed

#514 FIX_GROUP_VERIF_ENTITY
  src/Entity/Actuality.php
  src/Entity/Event.php
  src/Entity/Member.php
  src/Entity/Partner.php
Labels: Reviewed

#517 added image
  templates/admin/admin_event/index.html.twig
Labels: Conflicts resolved

#493 MIRGATION_PROD
  migrations/Version20220616140018.php
  migrations/Version20220618081549.php
  migrations/Version20220622141817.php
  migrations/Version20220622150015.php
  migrations/Version20220623091553.php
  migrations/Version20220623102151.php
  migrations/Version20220623131522.php
  migrations/Version20220627134054.php
  migrations/Version20220627135141.php
  migrations/Version20220627142737.php
  migrations/Version20220704133128.php
  migrations/Version20220704150554.php
  migrations/Version20220704153150.php
  migrations/Version20220705181612.php
  migrations/Version20220707144527.php
  migrations/Version20220713075416.php
Labels: Reviewed, Correction done, Fix

#518 FIX_PARTNER_URL
  src/Entity/Partner.php
Labels: Reviewed

#519 FIX_AOS
  templates/actuality/index.html.twig
  templates/components/_card_event.html.twig
  templates/components/_card_event_past.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#520 FIX_IMG_CADRE
  templates/actuality/show.html.twig
  templates/association/index.html.twig
  templates/event/_eventList.html.twig
  templates/event/show.html.twig
Labels: Reviewed

#522 dev to main
  assets/images/footer.webp
  assets/styles/app.scss
  migrations/Version20220616140018.php
  migrations/Version20220618081549.php
  migrations/Version20220622141817.php
  migrations/Version20220622150015.php
  migrations/Version20220623091553.php
  migrations/Version20220623102151.php
  migrations/Version20220623131522.php
  migrations/Version20220627134054.php
  migrations/Version20220627135141.php
  migrations/Version20220627142737.php
  migrations/Version20220704133128.php
  migrations/Version20220704150554.php
  migrations/Version20220704153150.php
  migrations/Version20220705181612.php
  migrations/Version20220707144527.php
  migrations/Version20220713075416.php
  src/Entity/Partner.php
  templates/actuality/index.html.twig
  templates/actuality/show.html.twig
  templates/admin/admin_event/index.html.twig
  templates/association/index.html.twig
  templates/components/_card_event.html.twig
  templates/components/_card_event_past.html.twig
  templates/event/_eventList.html.twig
  templates/event/show.html.twig
  templates/home/index.html.twig
Labels: DEV TO MAIN

#533 fix_buttons_contact
  templates/contact/_contactForm.html.twig
Labels: Reviewed, Fix

#529 added images for admin membres et actu
  templates/admin/admin_actuality/index.html.twig
  templates/admin/admin_member/index.html.twig
Labels: Reviewed, Fix

#536 FIX_ACTU
  templates/admin/admin_actuality/index.html.twig
  templates/admin/admin_event/index.html.twig
Labels: Reviewed, Fix

#527 Add icons
  templates/actuality/index.html.twig
  templates/components/_banner.html.twig
  templates/components/_card_event.html.twig
  templates/components/_card_event_past.html.twig
  templates/home/index.html.twig
Labels: Conflicts resolved

#534 fix_mentions_leg
  templates/legal-notice/index.html.twig
Labels: Correction done, Fix, Review needed

#537 fix_home_i
  templates/home/index.html.twig
Labels: Reviewed, Fix

#538 DEV TO MAIN
  src/DataFixtures/ActualityFixtures.php
  src/DataFixtures/actu.webp
  templates/actuality/index.html.twig
  templates/admin/admin_actuality/index.html.twig
  templates/admin/admin_event/index.html.twig
  templates/admin/admin_member/index.html.twig
  templates/components/_banner.html.twig
  templates/components/_card_event.html.twig
  templates/components/_card_event_past.html.twig
  templates/contact/_contactForm.html.twig
  templates/home/index.html.twig
  templates/legal-notice/index.html.twig
Labels: DEV TO MAIN

#535 fix_home_no_event
  templates/home/index.html.twig
Labels: Conflicts resolved

#539 fix_admin_th
  templates/admin/admin_actuality/index.html.twig
  templates/admin/admin_event/index.html.twig
Labels: Reviewed, Fix

#540 button style actus et événements
  templates/actuality/index.html.twig
  templates/home/index.html.twig
Labels: Reviewed, Fix

#541 resize img_footer
  assets/images/footer.webp
Labels: Reviewed

#542 style du bouton nous rejoindre
  templates/components/_banner.html.twig
Labels: Reviewed, Fix

#532 fix de l'orthographe
  config/packages/twig.yaml
  templates/admin/partner/index.html.twig
  templates/association/index.html.twig
  templates/components/_navbar.html.twig
  templates/event/_participant.html.twig
  templates/event/index.html.twig
  templates/home/index.html.twig
Labels: Reviewed, Conflicts resolved

#545 fix_titile_mentions_leg
  templates/legal-notice/index.html.twig
Labels: Reviewed

#544 fix_responsive_style
  assets/styles/app.scss
  templates/admin/admin_member/index.html.twig
  templates/components/_members.html.twig
  templates/components/_partners.html.twig
  templates/event/_participant.html.twig
  templates/home/index.html.twig
Labels: Reviewed, Conflicts resolved

#547 DEV TO MAIN
  assets/styles/app.scss
  config/packages/twig.yaml
  templates/admin/admin_actuality/_delete_form.html.twig
  templates/admin/admin_actuality/index.html.twig
  templates/admin/admin_event/_delete_form.html.twig
  templates/admin/admin_event/index.html.twig
  templates/admin/admin_member/_delete_form.html.twig
  templates/admin/admin_member/index.html.twig
  templates/admin/partner/_delete_form.html.twig
  templates/admin/partner/index.html.twig
  templates/association/index.html.twig
  templates/components/_members.html.twig
  templates/components/_navbar.html.twig
  templates/components/_partners.html.twig
  templates/event/_participant.html.twig
  templates/event/index.html.twig
  templates/home/index.html.twig
  templates/legal-notice/index.html.twig
Labels: DEV TO MAIN
