Repository WildCodeSchool/2022-03-php-orleans-project-splitscreen, pull requests merged in 2022-06, with the labels that each got.

#2 fonts var
  assets/styles/app.scss
  assets/styles/variables.scss
  templates/home/index.html.twig
Labels: Reviewed

#4 dev to main
  assets/app.js
  assets/images/LOGO_WILD_CODE_SCHOOL.png
  assets/images/favicon.png
  assets/styles/_wcs.scss
  assets/styles/app.scss
  assets/styles/variables.scss
  package.json
  templates/base.html.twig
  templates/home/index.html.twig
  yarn.lock
Labels: Review needed

#3 fix fonts
  assets/styles/variables.scss
Labels: Reviewed, Correction done

#32 base html fix
  templates/base.html.twig
Labels: Reviewed, Fix

#35 add BI
  assets/app.js
  package.json
  templates/home/index.html.twig
  yarn.lock
Labels: Reviewed, Fix

#33 S01 hnc01 navbar
  assets/images/LogoSplitScreen.png
  assets/styles/app.scss
  templates/_navbar.html.twig
  templates/base.html.twig
Labels: Reviewed, Conflicts, Conflicts resolved

#34 S01 hnc02 footer
  templates/_footer.html.twig
  templates/base.html.twig
Labels: Reviewed, Conflicts, Conflicts resolved

#41 dev to main fast pls
  .github/workflows/main.yml
  assets/app.js
  assets/images/LogoSplitScreen.png
  assets/images/img_contact.jpg
  assets/styles/app.scss
  assets/styles/variables.scss
  composer.json
  composer.lock
  config/packages/framework.yaml
  config/packages/mailer.yaml
  package.json
  src/Controller/ContactController.php
  src/Form/ContactType.php
  templates/_footer.html.twig
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/contact/_email.html.twig
  templates/contact/index.html.twig
  templates/home/index.html.twig
  yarn.lock
Labels: Reviewed, 🚨 URGENT 🚨

#42 S01 hnc10 rs contact
  assets/images/rs_contact.jpg
  templates/contact/index.html.twig
Labels: Reviewed, Correction done

#43 S01HNC20_HeaderImg
  assets/images/Gaming.jpg
  assets/styles/header.scss
  templates/_HeaderImg.html.twig
  templates/base.html.twig
  webpack.config.js
Labels: Reviewed, Conflicts resolved

#78 fixed header file name
  templates/_headerImg.html.twig
Labels: Reviewed

#44 S01 hnc07 evenement passe
  assets/images/clash-royale-esport-min.jpg
  assets/styles/event.scss
  composer.json
  composer.lock
  migrations/Version20220612081345.php
  src/Controller/EventController.php
  src/DataFixtures/EventFixtures.php
  src/Entity/Event.php
  src/Repository/EventRepository.php
  symfony.lock
  templates/event/index.html.twig
  webpack.config.js
Labels: Conflicts resolved

#40 S01 hnc5 structure asso
  .github/workflows/main.yml
  assets/images/mannettes.jpg
  assets/images/mannettes2.jpg
  src/Controller/AssociationController.php
  templates/association/index.html.twig
  templates/base.html.twig
Labels: Conflicts resolved

#84 S02HNC_FIX_Header
  assets/styles/header.scss
  templates/_header.html.twig
  templates/contact/index.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#77 S02 hnc fix footer
  templates/_footer.html.twig
  templates/contact/index.html.twig
Labels: Conflicts resolved

#98 S02HNC_FIX_Footer
  templates/_footer.html.twig
Labels: Reviewed

#88 S02 us33 admin acceuil
  src/Controller/AdminHomeController.php
  templates/admin/_navbarAdmin.html.twig
  templates/admin/admin_home/index.html.twig
  templates/admin/baseAdmin.html.twig
Labels: Reviewed, Correction done

#99 Fix : Date évènement
  migrations/Version20220614142018.php
  src/DataFixtures/EventFixtures.php
  src/Entity/Event.php
  templates/event/index.html.twig
Labels: Reviewed, Correction done

#106 Fix login path bug
  config/packages/security.yaml
  templates/login/index.html.twig
Labels: Reviewed, Fix

#115 finished corners
  assets/styles/association.scss
  templates/association/index.html.twig
  webpack.config.js
Labels: Reviewed, Correction done, Fix

#97 So02 us20 add events
  config/packages/twig.yaml
  migrations/Version20220614144635.php
  src/Controller/AdminEventController.php
  src/Entity/Event.php
  src/Form/EventType.php
  templates/admin_event/_delete_form.html.twig
  templates/admin_event/_form.html.twig
  templates/admin_event/edit.html.twig
  templates/admin_event/index.html.twig
  templates/admin_event/new.html.twig
  templates/admin_event/show.html.twig
Labels: Reviewed, Correction done

#120 S01 hnc74 description evenement
  assets/styles/event.scss
  migrations/Version20220613084814.php
  migrations/Version20220614144635.php
  migrations/Version20220615152524.php
  src/Controller/EventController.php
  src/DataFixtures/EventFixtures.php
  src/Entity/Event.php
  templates/event/index.html.twig
  templates/event/show.html.twig
Labels: Change requested

#124 dossier documents en ésperant que ca bug pas
  templates/association/index.html.twig
  templates/base.html.twig
  templates/components/_footer.html.twig
  templates/components/_header.html.twig
  templates/components/_navbar.html.twig
  templates/contact/index.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#126 dev to main
  .github/workflows/main.yml
  assets/images/Gaming.jpg
  assets/images/Helloasso-logo.png
  assets/images/LogoSplitScreen.png
  assets/images/clash-royale-esport-min.jpg
  assets/images/manette.jpg
  assets/images/mannettes.jpg
  assets/images/mannettes2.jpg
  assets/styles/association.scss
  assets/styles/banner.scss
  assets/styles/event.scss
  assets/styles/header.scss
  assets/styles/home.scss
  assets/styles/navbar.scss
  composer.json
  composer.lock
  config/packages/security.yaml
  config/packages/twig.yaml
  config/routes.yaml
  migrations/Version20220615152524.php
  src/Controller/AdminEventController.php
  src/Controller/AdminHomeController.php
  src/Controller/AssociationController.php
  src/Controller/ContactController.php
  src/Controller/EventController.php
  src/Controller/HomeController.php
  src/Controller/LoginController.php
  src/DataFixtures/EventFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Event.php
  src/Entity/User.php
  src/Form/ContactType.php
  src/Form/EventType.php
  src/Repository/EventRepository.php
  src/Repository/UserRepository.php
  symfony.lock
  templates/_footer.html.twig
  templates/admin/_navbarAdmin.html.twig
  templates/admin/admin_home/index.html.twig
  templates/admin/baseAdmin.html.twig
  templates/admin_event/_delete_form.html.twig
  templates/admin_event/_form.html.twig
  templates/admin_event/edit.html.twig
  templates/admin_event/index.html.twig
  templates/admin_event/new.html.twig
  templates/admin_event/show.html.twig
  templates/association/index.html.twig
  templates/base.html.twig
  templates/components/_banner.html.twig
  templates/components/_footer.html.twig
  templates/components/_header.html.twig
  templates/components/_navbar.html.twig
  templates/contact/index.html.twig
  templates/event/index.html.twig
  templates/event/show.html.twig
  templates/home/index.html.twig
  templates/login/index.html.twig
  webpack.config.js
Labels: DEV TO MAIN

#128 changed english to french
  templates/admin_event/_delete_form.html.twig
Labels: Reviewed, Correction done

#133 fix du trait et de la baniere
  assets/styles/event.scss
  templates/event/index.html.twig
Labels: Reviewed, Fix

#134 fr for errors
  config/packages/translation.yaml
Labels: Reviewed, Fix

#135 flash in base
  templates/base.html.twig
  templates/components/_flash.html.twig
  templates/contact/index.html.twig
Labels: Reviewed, Fix

#136 fixed modification form
  templates/admin_event/edit.html.twig
Labels: Conflicts resolved

#138 list-Button-Management-Fix
  templates/admin/admin_event/_delete_form.html.twig
  templates/admin/admin_event/index.html.twig
Labels: Fix, Conflicts resolved

#140 Added admin_event in admin folder
  templates/admin/admin_event/edit.html.twig
Labels: Fix, Conflicts resolved

#139 fixed placement and buttons
  templates/admin/admin_event/edit.html.twig
  templates/admin/admin_event/show.html.twig
  templates/admin_event/edit.html.twig
Labels: Fix, Conflicts resolved

#141 fixed template links
  templates/admin/admin_event/edit.html.twig
  templates/admin/admin_event/index.html.twig
Labels: Reviewed, Fix

#137 S02HNC12_Event
  assets/images/Atelier.jpg
  assets/images/TablesRondes.jpg
  assets/images/Tournois1.jpg
  templates/contact/index.html.twig
  templates/event/_eventList.html.twig
  templates/event/index.html.twig
Labels: Conflicts

#143 FIX_Navbar
  templates/components/_navbar.html.twig
Labels: Reviewed, Fix

#144 Fix_home_event.description -> event.catchPhrase
  templates/home/index.html.twig
Labels: Reviewed, Fix

#145 FIX_Banner
  templates/actuality/index.html.twig
  templates/event/index.html.twig
Labels: Reviewed, Fix

#146 FIX_Banner_img
  templates/event/index.html.twig
Labels: Reviewed, Fix

#149 Corners Responsive
  assets/styles/association.scss
  templates/association/index.html.twig
Labels: Reviewed, Fix

#151 fix home
  templates/home/index.html.twig
Labels: Reviewed, Fix

#152 Fix_redirection_detail_evenement_depuis_home
  templates/home/index.html.twig
Labels: Reviewed, Fix

#153 FIX_Event_responsive
  templates/event/_eventList.html.twig
Labels: Reviewed, Fix

#154 FIX_Banner_home
  templates/home/index.html.twig
Labels: Reviewed, Fix

#155 FIX_Style_event_Actuality_Association
  templates/actuality/index.html.twig
  templates/association/index.html.twig
  templates/event/index.html.twig
Labels: Reviewed, Fix

#156 fix button
  src/Form/ContactType.php
  templates/contact/index.html.twig
Labels: Reviewed, Fix

#158 FIX_Couleur_banner
  assets/images/Helloasso-logo.png
Labels: Reviewed, Fix

#159 fix add icon
  templates/components/_footer.html.twig
Labels: Reviewed, Fix

#185 dev to main
  assets/images/Helloasso-logo.png
  assets/styles/association.scss
  src/Form/ContactType.php
  templates/actuality/index.html.twig
  templates/association/index.html.twig
  templates/components/_footer.html.twig
  templates/contact/index.html.twig
  templates/event/_eventList.html.twig
  templates/event/index.html.twig
  templates/home/index.html.twig
Labels: DEV TO MAIN

#221 FIX_Banner
  templates/components/_banner.html.twig
Labels: Reviewed

#222 added font variables
  assets/styles/variables.scss
Labels: Reviewed, Fix

#224 fixed route naming /admin/accueil ====> /admin
  src/Controller/AdminHomeController.php
Labels: Reviewed, Fix

#219 FIX_Navbar
  templates/base.html.twig
  templates/components/_navbar.html.twig
Labels: Reviewed, Correction done

#225 FIX_Footer
  templates/components/_footer.html.twig
Labels: Reviewed, Correction done

#228 FIX_Header
  assets/images/Gaming.jpg
  assets/images/Gaming.webp
  assets/styles/header.scss
Labels: Reviewed

#229 FIX_Navbar_Hover
  assets/styles/navbar.scss
Labels: Reviewed

#230 FIX_Navbar_MediaQ
  assets/styles/navbar.scss
Labels: Conflicts resolved

#238 font fixed
  templates/contact/index.html.twig
Labels: Reviewed, Fix

#236 FIX_Scroll
  assets/styles/app.scss
Labels: Reviewed, Fix

#235 FIX_Footer
  templates/components/_footer.html.twig
Labels: Reviewed, Fix

#237 Dev To Main
  assets/images/Gaming.jpg
  assets/images/Gaming.webp
  assets/styles/app.scss
  assets/styles/header.scss
  assets/styles/navbar.scss
  assets/styles/variables.scss
  src/Controller/AdminHomeController.php
  templates/admin/_navbarAdmin.html.twig
  templates/admin/admin_event/_form.html.twig
  templates/base.html.twig
  templates/components/_banner.html.twig
  templates/components/_footer.html.twig
  templates/components/_navbar.html.twig
  templates/contact/index.html.twig
Labels: DEV TO MAIN

#231 init + add actus
  src/Controller/AdminActualityController.php
  src/Form/ActualityType.php
  templates/admin/admin_actuality/_form.html.twig
  templates/admin/admin_actuality/new.html.twig
Labels: Reviewed, Correction done

#233 index+del
  templates/admin/admin_actuality/_delete_form.html.twig
  templates/admin/admin_actuality/index.html.twig
Labels: Change requested

#232 edit actu admin
  templates/admin/admin_actuality/edit.html.twig
Labels: Reviewed

#234 Fix actu home vue
  assets/styles/home.scss
  src/Controller/HomeController.php
  src/DataFixtures/ActualityFixtures.php
  templates/home/index.html.twig
Labels: Conflicts resolved

#240 edit + index Admin member
  templates/admin/admin_member/edit.html.twig
  templates/admin/admin_member/index.html.twig
Labels: Reviewed, Correction done

#245 Dev To Main
  assets/styles/home.scss
  src/Controller/AdminActualityController.php
  src/Controller/HomeController.php
  src/DataFixtures/ActualityFixtures.php
  src/Form/ActualityType.php
  templates/actuality/index.html.twig
  templates/admin/admin_actuality/_form.html.twig
  templates/admin/admin_actuality/edit.html.twig
  templates/admin/admin_actuality/new.html.twig
  templates/admin/admin_member/_delete_form.html.twig
  templates/admin/admin_member/edit.html.twig
  templates/admin/admin_member/index.html.twig
  templates/home/index.html.twig
Labels: DEV TO MAIN

#223 contact fixes
  assets/styles/contact.scss
  src/Form/ContactType.php
  templates/contact/index.html.twig
  webpack.config.js
Labels: Reviewed, Correction done

#239 Hnc26 admin add member
  migrations/Version20220618081549.php
  src/Controller/AdminMemberController.php
  src/Entity/Member.php
  src/Form/MemberType.php
  src/Repository/MemberRepository.php
  templates/admin/admin_member/_form.html.twig
  templates/admin/admin_member/new.html.twig
Labels: Reviewed, Correction done

#253 Fix_redirection_vers_la_page_show
  templates/home/index.html.twig
Labels: Reviewed, Fix

#254 ADMIN_ACTU_DEL_INDEX : lautre branch a bugger
  templates/admin/admin_actuality/_delete_form.html.twig
  templates/admin/admin_actuality/index.html.twig
Labels: Reviewed

#256 FIX_Event_Card
  templates/event/index.html.twig
Labels: Reviewed

#258 Fix - Links pour l'admin dans la Navbar
  templates/admin/_navbarAdmin.html.twig
Labels: Reviewed

#259 FIX_Header
  assets/styles/header.scss
  templates/components/_header.html.twig
Labels: Reviewed

#260 fixed buttons and put membres into a container
  templates/admin/admin_event/index.html.twig
  templates/admin/admin_member/index.html.twig
Labels: Reviewed, Correction done

#261 DEV TO MAIN
  assets/styles/event.scss
  assets/styles/header.scss
  src/Controller/EventController.php
  templates/admin/_navbarAdmin.html.twig
  templates/admin/admin_event/index.html.twig
  templates/admin/admin_member/index.html.twig
  templates/components/_header.html.twig
  templates/event/index.html.twig
  templates/event/show.html.twig
  templates/home/index.html.twig
Labels: DEV TO MAIN

#265 fix_de_la_page_index_dans_admin_member
  templates/admin/admin_member/index.html.twig
Labels: Reviewed, Fix

#268 FIX_Home_Style
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed, Fix

#270 Fix_general_admin
  templates/admin/_navbarAdmin.html.twig
  templates/admin/admin_actuality/index.html.twig
  templates/admin/admin_event/_delete_form.html.twig
  templates/admin/admin_event/index.html.twig
  templates/admin/admin_member/index.html.twig
Labels: Reviewed, Fix

#273 FIX_Catch_phrase_Admin
  migrations/Version20220622150015.php
  src/Controller/AdminEventController.php
  src/Entity/Event.php
  src/Form/EventType.php
  templates/admin/admin_event/_form.html.twig
  templates/admin/admin_event/index.html.twig
  templates/admin/admin_event/show.html.twig
Labels: Conflicts resolved

#275 Fix form contact entity
  src/Controller/ContactController.php
  src/Entity/ContactForm.php
  src/Form/ContactFormType.php
  templates/contact/_contactForm.html.twig
  templates/contact/_networks.html.twig
  templates/contact/index.html.twig
Labels: Reviewed, Correction done, Fix

#266 HNC 41 add flash msg
  src/Controller/AdminActualityController.php
  src/Controller/AdminEventController.php
  src/Controller/AdminMemberController.php
Labels: Reviewed, Correction done

#272 Admin Crud for Networks
  migrations/Version20220622141817.php
  src/Controller/AdminNetworkController.php
  src/Entity/Network.php
  src/Form/NetworkType.php
  src/Repository/NetworkRepository.php
  templates/admin/admin_network/_form.html.twig
  templates/admin/admin_network/edit.html.twig
  templates/admin/admin_network/index.html.twig
Labels: Reviewed, Correction done

#278 added assert entity actu
  src/Entity/Actuality.php
Labels: Reviewed, Fix

#282 FIX_BOUTON_FORM_CONTACT center button
  templates/contact/_contactForm.html.twig
Labels: Reviewed, Fix

#284 FIX_Shadow_Card
  templates/actuality/index.html.twig
  templates/event/index.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#289 FIX_Alignement
  templates/home/index.html.twig
Labels: Reviewed, Fix

#291 FIX_padding_Footer_actus
  templates/actuality/index.html.twig
Labels: Reviewed, Fix

#294 FIX_ACTUS_ADMIN
  src/Form/ActualityType.php
  templates/admin/admin_actuality/index.html.twig
Labels: Reviewed

#292 FIX_BOUTON_ADMIN harmonisation du style admin
  templates/admin/admin_actuality/_form.html.twig
  templates/admin/admin_actuality/edit.html.twig
  templates/admin/admin_actuality/new.html.twig
  templates/admin/admin_event/_delete_form.html.twig
  templates/admin/admin_event/_form.html.twig
  templates/admin/admin_event/edit.html.twig
  templates/admin/admin_event/index.html.twig
  templates/admin/admin_event/new.html.twig
  templates/admin/admin_member/_delete_form.html.twig
  templates/admin/admin_member/_form.html.twig
  templates/admin/admin_member/edit.html.twig
  templates/admin/admin_member/index.html.twig
  templates/admin/admin_member/new.html.twig
Labels: Reviewed, Correction done, Fix

#317 Fix_home
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed, Fix

#321 FIX_ACCUEIL_SEPARATE separte cards
  templates/home/index.html.twig
Labels: Reviewed, Fix

#319 removed footer
  templates/admin/baseAdmin.html.twig
  templates/login/index.html.twig
Labels: Reviewed

#323 FIX_FONT_CONTACTS bigger text
  templates/contact/_networks.html.twig
Labels: Reviewed, Fix

#315 S04HNC43_EDIT_PARTNERS edit partners
  templates/admin/partners/edit.html.twig
Labels: Reviewed

#316 S04HNC43_DEL_PARTNERS delete form
  templates/admin/partners/_delete_form.html.twig
  templates/admin/partners/_form.html.twig
Labels: Reviewed

#325 finished fixing corners
  assets/styles/app.scss
  assets/styles/association.scss
  assets/styles/event.scss
  assets/styles/eventShow.scss
  templates/actuality/show.html.twig
  templates/association/index.html.twig
  templates/event/_eventList.html.twig
  templates/event/index.html.twig
  templates/event/show.html.twig
  webpack.config.js
Labels: Reviewed

#330 added folder
  public/uploads/event/.gitignore
Labels: Reviewed

#314 S04HNC42_ADD_PARTNER init + add partner
  config/packages/vich_uploader.yaml
  migrations/Version20220627135141.php
  src/Controller/PartnerController.php
  src/Entity/Partner.php
  src/Form/PartnerType.php
  src/Repository/PartnerRepository.php
  templates/admin/partner/_delete_form.html.twig
  templates/admin/partner/_form.html.twig
  templates/admin/partner/edit.html.twig
  templates/admin/partner/index.html.twig
  templates/admin/partner/new.html.twig
Labels: Reviewed, Correction done

#331 fixed upload link
  templates/event/index.html.twig
Labels: Reviewed

#318 S04 hnc41 iframe
  migrations/Version20220627142737.php
  src/Entity/Event.php
  src/Form/EventType.php
  templates/admin/admin_event/_form.html.twig
  templates/event/show.html.twig
  templates/home/index.html.twig
Labels: Conflicts resolved

#333 fixed images acceuil
  templates/home/index.html.twig
Labels: Reviewed, Fix

#334 FIX_NAVBAR_PARTNERS fix
  templates/admin/_navbarAdmin.html.twig
  templates/admin/partner/_form.html.twig
Labels: Reviewed

#332 S04 hnc48 ckeditor
  composer.json
  composer.lock
  config/bundles.php
  config/packages/fos_ckeditor.yaml
  config/packages/twig.yaml
  package.json
  src/Entity/Actuality.php
  src/Form/ActualityType.php
  symfony.lock
  templates/actuality/show.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed, Correction done
